
drop table if exists ANEXO CASCADE;

CREATE TABLE ANEXO
(
  ID bigint NOT NULL,
  NOME_ARQUIVO CHARACTER VARYING(255),
  DIRETORIO CHARACTER VARYING(255),
  DATA_INCLUSAO DATE NOT NULL,
  CONSTRAINT PK_ID PRIMARY KEY (ID)
);
